# リポジトリ内の不要なファイルを見つけるためのGithub Actions
name: ChackUnwantedFiles

on:
  # GithubのActionsタブから手動で実行できるようにする
  workflow_dispatch:
  # masterブランチへのpushでも実行する
  push:
    branches:
      - master

# 検出する不要なファイルのパターンを定義する環境変数
env:
  # 特定のファイル名のパターン
  UNWANTED_NAME_PATTERNS: "*.pdb *ilk *.user *.ncb*.suo *.log *.dmp *.zip imgui.ini desktop.ini dxcompiler.dll dxil.dll"

  # ディレクトリ名のパターン
  UNWANTED_DIR_PATTERNS: "generated x64 win32 arm64 .vs bin ipch logs Dump"

jobs:
  check-files:
    name: 不要なファイルを検索
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 不要なファイルとディレクトリを検索
        run: |
          # ディレクトリ検索を構築
          DIR_CONDITIONS=()
          for pattern in $UNWANTED_DIR_PATTERNS; do
            DIR_CONDITIONS+=(-o -iname "$pattern")
          done
          unset DIR_CONDITIONS[0]
          # ファイル条件を構築
          NAME_CONDITIONS=()
          for pattern in $UNWANTED_NAME_PATTERNS; do
            NAME_CONDITIONS+=(-o -iname "$pattern")
          done
          unset NAME_CONDITIONS[0]

          # 1回のFind実行で全件を検索
          # 1. .git を除外
          # 2. 不要なディレクトリを検索し、見つけたらパスを出力してその中身を枝刈り
          # 2. または不要なファイルを検索しパスを出力
          UNWANTED_LIST=$(find . -path "./.git" -prune -o \
            \( \( "${DIR_CONDITIONS[@]}" \) -a -type d -print -prune \) -o \
            \( \( "${NAME_CONDITIONS[@]}" \) -a -type f -print \) \
          )

          # 検出結果があればエラーとして出力し失敗させる
          if [ -n "UNWANTED_LIST" ]; then
            echo "::error::不要なファイルまたはディレクトリが見つかりました！"
            echo "$UNWANTED_LIST"
            exit 1
          fi


          echo "リポジトリはクリーンです"